//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDEFEntities : DbContext
    {
        public BDEFEntities()
            : base("name=BDEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<administradores> administradores { get; set; }
        public virtual DbSet<encuestas> encuestas { get; set; }
        public virtual DbSet<metodos_de_pago> metodos_de_pago { get; set; }
        public virtual DbSet<ordenes> ordenes { get; set; }
        public virtual DbSet<pagos> pagos { get; set; }
        public virtual DbSet<reportes> reportes { get; set; }
        public virtual DbSet<sedes> sedes { get; set; }
        public virtual DbSet<tortas> tortas { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
