//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordenes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ordenes()
        {
            this.tortas = new HashSet<tortas>();
        }
    
        public int codigo { get; set; }
        public System.DateTime fecha_entrega { get; set; }
        public string direccion { get; set; }
        public string distrito { get; set; }
        public int cantidad { get; set; }
        public int precio { get; set; }
        public int usuarios_codigo { get; set; }
        public int administradores_codigo { get; set; }
        public int pagos_codigo { get; set; }
        public int sedes_codigo { get; set; }
    
        public virtual administradores administradores { get; set; }
        public virtual pagos pagos { get; set; }
        public virtual sedes sedes { get; set; }
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tortas> tortas { get; set; }
    }
}
