//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tortas
    {
        public int codigo { get; set; }
        public string nombre { get; set; }
        public string sabor { get; set; }
        public string tematica { get; set; }
        public string tamano { get; set; }
        public int ordenes_codigo { get; set; }
    
        public virtual ordenes ordenes { get; set; }
    }
}
